---
fullname: Mczify
shortname: mczify
opam_name: coq-mathcomp-zify
organization: math-comp
action: true

synopsis: >-
  Micromega tactics for Mathematical Components

description: |-
  This small library enables the use of the Micromega arithmetic solvers of Coq
  for goals stated with the definitions of the Mathematical Components library
  by extending the zify tactic.

authors:
- name: Kazuhiko Sakaguchi
  initial: true

opam-file-maintainer: kazuhiko.sakaguchi@ens-lyon.fr

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.18 or later
  opam: '{>= "8.18"}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '2.3.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '2.3.0-coq-8.19'
  repo: 'mathcomp/mathcomp'
- version: '2.3.0-coq-8.20'
  repo: 'mathcomp/mathcomp'
- version: '2.4.0-coq-8.19'
  repo: 'mathcomp/mathcomp'
- version: '2.4.0-coq-8.20'
  repo: 'mathcomp/mathcomp'
- version: '2.4.0-rocq-prover-9.0'
  repo: 'mathcomp/mathcomp'
- version: '2.4.0-rocq-prover-dev'
  repo: 'mathcomp/mathcomp'
- version: 'rocq-prover-9.0'
  repo: 'mathcomp/mathcomp-dev'
- version: 'rocq-prover-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{>= "2.3"}'
  description: |-
    [MathComp](https://math-comp.github.io) ssreflect 2.3 or later
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp](https://math-comp.github.io) algebra

test_target: test-suite
namespace: mathcomp.zify

action_appendix: |2-
            export: 'OPAMWITHTEST'
          env:
            OPAMWITHTEST: true

documentation: |-
  ## File contents

  - `zify_ssreflect.v`: Z-ification instances for the `coq-mathcomp-ssreflect`
    library
  - `zify_algebra.v`: Z-ification instances for the `coq-mathcomp-algebra`
    library
  - `zify.v`: re-exports all the Z-ification instances
  - `ssrZ.v`: provides a minimal facility for reasoning about `Z` and relating
    `Z` and `int`

---
