---
fullname: mczify
shortname: mczify
organization: math-comp
action: true

synopsis: >-
  Micromega tactics for Mathematical Components

description: |-
  This small library enables the use of the Micromega tactics for goals stated
  with the definitions of the Mathematical Components library by extending the
  zify tactic.

authors:
- name: Kazuhiko Sakaguchi
  initial: true

opam-file-maintainer: sakaguchi@coins.tsukuba.ac.jp

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.13 or later
  opam: '{(>= "8.13" & < "8.14~") | (= "dev")}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-dev'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.13'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-algebra
    version: '{(>= "1.12" & < "1.13~") | (= "dev")}'
  nix: mathcomp-algebra
  description: |-
    [MathComp](https://math-comp.github.io) 1.12.0 or later

namespace: mathcomp.zify
---
